# Generated by Django 5.2.8 on 2025-12-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_whiskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiskey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whiskey',
            name='sale_price',
        ),
    ]
