# Generated by Django 5.2.8 on 2025-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_whiskey_description_remove_whiskey_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='category',
            field=models.CharField(choices=[('Scotch', 'Scotch'), ('Bourbon', 'Bourbon'), ('Cognac', 'Cognac')], default='Scotch', max_length=50),
        ),
    ]
