# Generated by Django 5.2.8 on 2025-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_whiskey_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiskey',
            name='category',
            field=models.CharField(choices=[('Scotch', 'Scotch'), ('Bourbon', 'Bourbon'), ('Cognac', 'Cognac'), ('Indian ', 'SIndian '), ('Single malt', 'Single malt'), ('Blended scotch', 'Blended scotch ')], default='Scotch', max_length=50),
        ),
    ]
