# Generated by Django 5.2.8 on 2025-12-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_whiskey_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Red wine', 'Red wine'), ('White wine', 'White wine'), ('Rose wine', 'Rose wine'), ('Sparkling wine', 'Sparkling wine'), ('Single malt', 'Single malt'), ('Port wine', 'Port wine'), ('Red sweet wine', 'Red sweet wine'), ('White sweet wine', 'White sweet wine'), ('White dry wine', 'White wine'), ('Red dry wine', 'Red dry wine')], default='Scotch', max_length=50)),
                ('abv', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='beer/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('London dry gin', 'London dry gin'), ('Flavoured gin', 'Flavoured gin'), ('Sloe gin', 'Sloe gin'), ('Plymouth gin', 'Plymouth gin'), ('International style gin', 'International style gin')], default='Scotch', max_length=50)),
                ('abv', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='Gin/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
