# Generated by Django 5.2.8 on 2025-12-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_beer_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('whiskey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.whiskey')),
            ],
        ),
    ]
