# Generated by Django 5.2.8 on 2025-12-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
