# Generated by Django 5.2.8 on 2025-12-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.AlterField(
            model_name='gin',
            name='category',
            field=models.CharField(choices=[('London dry gin', 'London dry gin'), ('Flavoured gin', 'Flavoured gin'), ('Sloe gin', 'Sloe gin'), ('Plymouth gin', 'Plymouth gin'), ('Old Tom gin', 'Old Tom gin'), ('Genever gin', 'Genever gin'), ('Navy strength gin', 'Navy strength gin'), ('Barrel-aged gin', 'Barrel-aged gin'), ('New Western gin', 'New Western gin'), ('Botanical gin', 'Botanical gin'), ('Contemporary gin', 'Contemporary gin'), ('International style gin', 'International style gin')], default='London dry gin', max_length=50),
        ),
    ]
