# Generated by Django 5.2.8 on 2025-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_beer_alter_gin_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('lager', 'Lager'), ('stout', 'Stout'), ('ale', 'Ale'), ('pilsner', 'Pilsner'), ('cider', 'Cider'), ('other', 'Other')], default='Ale', max_length=50)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=4)),
                ('volume', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='beers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
